### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by darshanr27** [darshanr27/real-estate-project#2]
At now the website is viewed only at the desktop,  make it responsive to mobile devices.

**Comment by gebleksengek** [comment]
Hey @darshanr27  I would like work on this, can you please assign this to me?

**Comment by glowreeya-01** [comment]
Hi @darshanr27. 
Can I work on this?  Would be really glad to do so.

**Comment by darshanr27** [comment]
You can go through it.

**Comment by darshanr27** [comment]
> Hey @darshanr27 I would like work on this, can you please assign this to me?

**Assigned**

**Comment by gebleksengek** [comment]
#3

**Comment by purnima143** [comment]
If the issue is not sorted yet, can I work on this issue?

**Comment by darshanr27** [comment]
> If the issue is not sorted yet, can I work on this issue?
@purnima143 Thank you for your interest.  But this issue is already assigned and coding is almost done.
